ModelLiquidFuels: 1 #Flag to turn or off Syn Fuel modelling capabilities - 0 - no SF, 1- SF modeled

AllowConventionalDiesel: 1
SpecifyConvDieselPercentFlag: 0
percent_conv_diesel: 0.1

AllowConventionalJetfuel: 1
SpecifyConvJetfuelPercentFlag: 0
percent_conv_jetfuel: 0.1

AllowConventionalGasoline: 1
SpecifyConvGasolinePercentFlag: 0
percent_conv_gasoline: 0.1