H2PipeInteger: 0
H2CO2Cap: 0
NetworkExpansion: 1
TimeDomainReductionFolder: "TDR_Results"
ModelingToGenerateAlternativeIterations: 3
SystemCO2Constraint: 0
H2G2PCommit: 0
ModelH2Trucks: 1
ParameterScale: 0
H2NetworkExpansion: 1
EnergyShareRequirement: 0
PrintModel: 0
TimeDomainReduction: 1
Trans_Loss_Segments: 1
CapacityReserveMargin: 0
LogFile: "output.log"
ModelingtoGenerateAlternativeSlack: 0.1
Solver: "Gurobi"
MethodofMorris: 0
ModelH2G2P: 1
LongDurationStorage: 0
ModelH2Liquid: 1
Reserves: 0
StorageLosses: 1
Log: true
OperationWrapping: 1
OverwriteResults: 0
UCommit: 0
H2GenCommit: 0
ModelingToGenerateAlternatives: 0
MaxCapReq: 0
MinCapReq: 0
CO2Cap: 2
ModelH2: 1
H2TrucksMaxDistance: 500
WriteShadowPrices: 1
ModelH2Pipelines: 1
