ModelCO2: 0 #Flag to turn or off Carbon Supply Chain modelling capabilities - 0 - no CSC, 1- CSC modeled

#To be edited and added in future modules
CO2PipeInteger: 0 # Whether to model pipeline capacity as discrete or integer - 0 - continuous capacity, 1- discrete capacity
ModelCO2Pipelines: 1 # Whether to model pipeline in CO2 supply chain - 0 - not included, 1 - included
CO2CaptureCommit: 0 # Continuous or discrete capacity representation of CO2 capture technologies with unit commitment; 0 = modeled as continuous variables; 1 = modeled as integer variables;
CO2NetworkExpansion: 1 # Transmission network expansional; 0 = not active; 1 = active systemwide
CO2CostOffset: 0 # Emissions offset via a carbon price; 0 = not active ; 1 = active

CO2CO2Cap: 0 # CO2 emissions cap for CSC only; 0 = not active (no CO2 emission limit); 1 = mass-based emission limit constraint; 2 = load + rate-based emission limit constraint; 3 = generation + rate-based emission limit constraint; 4 = emissions penalized via a carbon price
