ModelCSC: 1 #Flag to turn or off Carbon Supply Chain modelling capabilities - 0 = no CSC, 1= CSC modeled

ModelBIO: 0
ModelSynFuels: 0

CO2PipeInteger: 0 # Whether to model pipeline capacity as discrete or integer 0 = continuous capacity, 1 = discrete capacity
ModelCO2Pipelines: 1 # Whether to model pipeline in CO2 supply chain - 0 = not included, 1 = included
CO2NetworkExpansion: 1 # Transmission network expansional; 0 = not active; 1 = active systemwide

CO2Pipeline_Loss: 1 #Loss of CO2 from pipelines

Exogeneous_CO2_Demand: 1
CO2CaptureTarget: 0
