ModelLiquidFuels: 1 #Flag to turn or off Syn Fuel modelling capabilities - 0 - no SF, 1- SF modeled

AllowConventionalDiesel: 0
SpecifySynBioDieselPercentFlag: 0
percent_sbf_diesel: 0.1

AllowConventionalJetfuel: 0
SpecifySynBioJetfuelPercentFlag: 0
percent_sbf_jetfuel: 0.1

AllowConventionalGasoline: 0
SpecifySynBioGasolinePercentFlag: 0
percent_sbf_gasoline: 0.1