name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ["bug"]
projects: ["macroenergy/DOLPHYN"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Please list the steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Julia**: 1.67
        - **Solver**: Gurobi
        - **Solver version**: 10.0
    value: |
        - OS:
        - Julia version:
        - Solver:
        - Solver version:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Manifest.toml file
    description: |
      Please upload or paste your Manifest.toml file here. GitHub will not allow you to upload a file with the extension .toml, so you will need to change the extension to .txt before uploading.
      
      The Manifest.toml file will be created after you first instantiate the DOLPHYN environment on your own computer.
    placeholder: |
      Upload your Manifest.toml file here. Change the file extension to .txt before uploading.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
