name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature", "additions"]
projects: ["DOLPHYN/", "GenX/"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-feature
    attributes:
      label: What new feature do you propose?
      description: What new feature do you propose?
      placeholder: Tell us what you expect to see for this project!
      value: "Tell us what you expect to see for this project!"
    validations:
      required: true
  - type: textarea
    id: suggestion-to-implement
    attributes:
      label: What suggestion do you have for implementing this feature?
      description: What suggestion do you have for implementing this feature?
      placeholder: Provide us with your suggestion
      value: "Tell us your way to implement this feature. Any suggestions?"
    validations:
      required: false
