ModelCSC: 1 #Flag to turn or off Carbon Supply Chain modelling capabilities - 0 = no CSC, 1= CSC modeled

#Linear modeling of DAC CAPEX - 0, Piecewise modeling of 6/10 rule of DAC CAPEX - 1
DAC_Nonlinear_CAPEX: 0
#Specify the number of piecewise segments if modeling nonlinear CAPEX based on 6/10 rule for DAC
DAC_CAPEX_Piecewise_Segments: 3

Exogeneous_CO2_Demand: 0 #Flag to turn or off Carbon Supply Chain exogenous demand - 0 = No Exogenous CO2 Demand, 1 = With Exogenous CO2 Demand
CO2CaptureTarget: 0 #Flag to turn or off Carbon Supply Chain CO2 capture target - 0 = No CO2 Capture Target, 1 = With CO2 Capture Target

CO2PipeInteger: 0 # Whether to model pipeline capacity as discrete or integer 0 = continuous capacity, 1 = discrete capacity
ModelCO2Pipelines: 1 # Whether to model pipeline in CO2 supply chain - 0 = not included, 1 = included
CO2NetworkExpansion: 1 # Transmission network expansional; 0 = not active; 1 = active systemwide

CO2Pipeline_Loss: 0 #Loss of CO2 from pipelines
