ModelCO2: 0 #Flag to turn or off Carbon Supply Chain modelling capabilities - 0 - no CSC, 1- CSC modeled

#Linear modeling of CAPEX - 0, Piecewise modeling of 6/10 rule of CAPEX - 1, 
DAC_CAPEX_Piecewise: 0
CO2_Injection_CAPEX_Piecewise: 0
CO2_Capture_Comp_CAPEX_Piecewise: 0

CO2PipeInteger: 0 # Whether to model pipeline capacity as discrete or integer - 0 - continuous capacity, 1- discrete capacity
ModelCO2Pipelines: 0 # Whether to model pipeline in CO2 supply chain - 0 - not included, 1 - included
CO2NetworkExpansion: 0 # Transmission network expansional; 0 = not active; 1 = active systemwide

CO2Pipeline_Loss: 0 #Loss of CO2 from pipelines