name: Documentation
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DOLPHYN
        uses: actions/checkout@v4
        with: 
          submodules: 'recursive'
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1.7
        with:
          version: '1.8.5'
          arch: 'x64'
      - name: Cache for speed
        uses: julia-actions/cache@v1
        with:
          cache-registries: "true"
      - uses: julia-actions/julia-buildpkg@v1
      - name: Build docs and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with documenter
        run: 
            julia --project=docs docs/make.jl
