on:
  pull_request:
    branches:
      - main
    paths:
      - '**.jl'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v1.2.2
        with:
          cache-registries: "true"
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - uses: julia-actions/julia-runtest@latest
        env:
          PYTHON: ""
