on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.jl'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: julia-actions/cache@v1.2.2
        with:
          cache-registries: "true"
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - uses: julia-actions/julia-runtest@latest
        env:
          PYTHON: ""
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "test/summary.txt"
      - name: Add PR Comment
        if: steps.check_files.outputs.files_exists == 'true'
        uses: mshick/add-pr-comment@v2
        with:
          message-path: |
            summary.txt
