name: Test OneZone Case
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.8'
      - name: Install dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'
      - name: Test case
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=@. Example_Systems/SmallNewEngland/OneZone/Run.jl
